// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePost = "post"

// Post mapped from table <post>
type Post struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PostID      int64     `gorm:"column:post_id;not null;comment:帖子id" json:"post_id"`                          // 帖子id
	Title       string    `gorm:"column:title;not null;comment:标题" json:"title"`                                // 标题
	Content     string    `gorm:"column:content;not null;comment:内容" json:"content"`                            // 内容
	AuthorID    int64     `gorm:"column:author_id;not null;comment:作者的用户id" json:"author_id"`                   // 作者的用户id
	CommunityID int64     `gorm:"column:community_id;not null;comment:所属社区" json:"community_id"`                // 所属社区
	Status      int32     `gorm:"column:status;not null;default:1;comment:帖子状态" json:"status"`                  // 帖子状态
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
