// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSession = "session"

// Session mapped from table <session>
type Session struct {
	SessionID    string    `gorm:"column:session_id;primaryKey" json:"session_id"`
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`
	RefreshToken string    `gorm:"column:refresh_token;not null" json:"refresh_token"`
	IsRevoked    bool      `gorm:"column:is_revoked;not null" json:"is_revoked"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	ExpiresAt    time.Time `gorm:"column:expires_at" json:"expires_at"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
