app:
  name: "app_demo"
  version: "0.1.0"
  mode: "dev"
  host: "0.0.0.0"
  port: 8081

log:
  level: "debug"
  filename: "app_demo.log"
  max_size: 200  # 200M
  max_age: 30    # 30days
  max_backups: 7

mysql:
  host: "10.211.55.3"
  port: 3306
  user: "golang"
  password: "123456"
  database: "sql_demo"

redis:
  host: "10.211.55.3"
  port: 6379
  password: "redis"
  db: 0

