// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demoProject/config"
	"demoProject/internal/api"
	"demoProject/internal/app"
	"demoProject/internal/infra"
	"demoProject/internal/infra/mysql"
	"demoProject/internal/infra/redis"
	"demoProject/internal/repo"
	"demoProject/internal/service"
)

// Injectors from wire.go:

func InitConfig() (*config.Config, error) {
	configConfig, err := config.InitConfig()
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}

func InitServer(cfg *config.Config) (*app.Server, func(), error) {
	engine := app.NewEngine()
	basicHandler := api.NewBasicHandler()
	db, err := mysql.InitDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	client, err := redis.InitRedis(cfg)
	if err != nil {
		return nil, nil, err
	}
	resources, cleanup, err := infra.NewResources(db, client)
	if err != nil {
		return nil, nil, err
	}
	iUserRepo := repo.NewMysqlUserRespository(resources)
	iUserService := service.NewUserService(iUserRepo)
	userHandler := api.NewUserHandler(iUserService)
	router := app.NewRouter(basicHandler, userHandler)
	server := app.NewServer(engine, router, cfg)
	return server, func() {
		cleanup()
	}, nil
}
