// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demoProject/config"
	"demoProject/internal/api"
	"demoProject/internal/app"
	"demoProject/internal/infra"
	"demoProject/internal/infra/mysql"
	"demoProject/internal/infra/redis"
	"demoProject/internal/repo"
	"demoProject/internal/service"
	"demoProject/pkg/util"
)

// Injectors from wire.go:

func InitConfig() (*config.Config, error) {
	configConfig, err := config.InitConfig()
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}

func InitServer(configConfig *config.Config) (*app.Server, func(), error) {
	engine := app.NewEngine(configConfig)
	basicHandler := api.NewBasicHandler()
	db, err := mysql.InitDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	client, err := redis.InitRedis(configConfig)
	if err != nil {
		return nil, nil, err
	}
	resources, cleanup, err := infra.NewResources(db, client)
	if err != nil {
		return nil, nil, err
	}
	iUserRepo := repo.NewMysqlUserRepository(resources)
	iSessionRepo := repo.NewMysqlSessionRepository(resources)
	envConfig, err := config.InitEnvConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	string2 := config.ProvideSecretKey(envConfig)
	jwtMaker := util.NewJWTMaker(string2)
	iUserService := service.NewUserService(iUserRepo, iSessionRepo, jwtMaker)
	userHandler := api.NewUserHandler(iUserService)
	iAuthService := service.NewAuthService(iSessionRepo, jwtMaker)
	authHandler := api.NewAuthHandler(iAuthService)
	iCommunityRepo := repo.NewMysqlCommunityRepository(resources)
	iCommunityService := service.NewCommunityService(iCommunityRepo)
	communityHandler := api.NewcommunityHandler(iCommunityService)
	iPostRepo := repo.NewMysqlPostRepository(db)
	iPostService := service.NewPostService(iPostRepo)
	postHandler := api.NewPostHandler(iPostService)
	router := app.NewRouter(configConfig, basicHandler, userHandler, authHandler, jwtMaker, communityHandler, postHandler)
	server := app.NewServer(engine, router, configConfig)
	return server, func() {
		cleanup()
	}, nil
}
