// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demoProject/config"
	"demoProject/internal/api"
	"demoProject/internal/app"
)

// Injectors from wire.go:

func InitConfig() (*config.Config, error) {
	configConfig, err := config.InitConfig()
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}

func InitServer(cfg *config.Config) (*app.Server, error) {
	engine := app.NewEngine()
	basicHandler := api.NewBasicHandler()
	router := app.NewRouter(basicHandler)
	server := app.NewServer(engine, router, cfg)
	return server, nil
}
